# Generated by Django 4.1.4 on 2023-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255)),
                ('sobrenome', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('idade', models.CharField(max_length=11, null=True)),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('genero', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('cadastro_criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cadastro_criado_em'],
            },
        ),
    ]
